PRJ_DIR  = test

SRC_DIR = $(PRJ_DIR)/src
BIN_DIR = $(PRJ_DIR)/bin

include Makefile.dirs




SRC_FILES	= $(wildcard $(SRC_DIR)/*.c)
BIN_FILES	= $(addprefix $(BIN_DIR)/,$(notdir $(SRC_FILES:.c=.exe)))


CFLAGS  = -static -Wall -O3 -I$(INC_DIR)
LFLAGS = -L$(RELEASE_DIR) -ldspl  -lplot -lfftw3 -lm

all: $(BIN_FILES)


$(BIN_DIR)/%.exe: $(SRC_DIR)/%.c
	$(CC)  $(CFLAGS)  $< $(LFLAGS)  -o $@ 


clean:
	rm -f   $(BIN_DIR)/*.exe

